name = "file-processor"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

[[processes]]
id = "process2"
name = "In Progress"

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "task1"
  title = "Define project structure and file handling approach"
  description = "Define how files will be read, processed, and how errors will be handled."
  tag = "in-progress"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ "Create main file-processing logic", "Handle errors gracefully" ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "task2"
  title = "Implement file reading and line processing"
  description = "Write the function that reads files concurrently and processes their contents."
  tag = "in-progress"
  linkFiles = [ ]
  dueDate = "2024-11-10"
  checkList = [ "Implement read_file function", "Filter empty lines" ]
  priority = "Medium"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "task3"
  title = "Set up error handling for file reading"
  description = "Handle any exceptions that may arise while reading files."
  tag = "in-progress"
  linkFiles = [ ]
  dueDate = "2024-11-10"
  checkList = [ "Add Deferred.catch for error handling" ]
  priority = "Medium"
  linkCommits = [ ]